"""
    BOAVIZTAPI - DEMO

    # 🎯 Retrieving the impacts of digital elements This is a quick demo, to see full documentation [click here](https://doc.api.boavizta.org)  ## ➡️Server router  ### Server routers support the following impacts:  | Impact | 🔨 Manufacture | 🔌 Usage | |--------|----------------|----------| |   GWP  |        X       |     X    | |   ADP  |        X       |     X    | |   PE   |        X       |     X    | ## ➡️Cloud router  ### Cloud routers support the following impacts:  | Impact | 🔨 Manufacture | 🔌 Usage | |--------|----------------|----------| |   GWP  |        X       |     X    | |   ADP  |        X       |     X    | |   PE   |        X       |     X    | ## ➡️Component router  ### Component routers support the following impacts:  | Impact | 🔨 Manufacture | 🔌 Usage | |--------|----------------|----------| |   GWP  |        X       |          | |   ADP  |        X       |          | |   PE   |        X       |          |   # noqa: E501

    The version of the OpenAPI document: 0.1.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import boaviztapi_sdk
from boaviztapi_sdk.model.cpu import Cpu
from boaviztapi_sdk.model.disk import Disk
from boaviztapi_sdk.model.power_supply import PowerSupply
from boaviztapi_sdk.model.ram import Ram
globals()['Cpu'] = Cpu
globals()['Disk'] = Disk
globals()['PowerSupply'] = PowerSupply
globals()['Ram'] = Ram
from boaviztapi_sdk.model.configuration_server import ConfigurationServer


class TestConfigurationServer(unittest.TestCase):
    """ConfigurationServer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigurationServer(self):
        """Test ConfigurationServer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConfigurationServer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
