#!/bin/bash

cd /usr/lib/python3/dist-packages/boagent
python3 -m venv --system-site-packages venv
source venv/bin/activate
python3 -m pip install boaviztapi-sdk
cd ..
python3 -m uvicorn boagent.api.api:app --host 127.0.0.1 --port 3000
